# Generates the app's baked data (Kotlin source):
#   MapData.kt   -- the post-CRL network schematic: lines, stations, labels,
#                   platforms, background, and GPS-snapping segments
#   RouteData.kt -- the 27H's stops in both directions, for the route map
#
#   AT_API_KEY=... python tools/gen_data.py
#
# The schematic layout comes from railview.py (shared with the ESP32 board,
# drawn after AT's official "Nga Tereina" network map).
import json, os, sys, urllib.request, datetime

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
import railview as R

OUT = os.path.join(HERE, "..", "app", "src", "main", "java", "nz", "aryan", "akllive", "data")
KEY = os.environ.get("AT_API_KEY", "")

DISPLAY = {"Waitemata": "Waitematā", "Orakei": "Ōrākei", "Otahuhu": "Ōtāhuhu",
           "Te Papapa": "Te Pāpapa", "Ranui": "Rānui", "Paerata": "Paerātā",
           "Te Mahia": "Te Māhia", "Sturges Rd": "Sturges Road", "Fruitvale": "Fruitvale Road"}
GTFS_NAME = {"Fruitvale": "Fruitvale Rd"}

# label placement: (anchor, dx, dy) in dp. l = text to the right, r = to the
# left, t = below, b = above. Priority 0 labels win collisions over 1, then 2.
LABEL = {
    "Swanson": ("l", 8, 0, 0), "Ranui": ("l", 8, 0, 2), "Sturges Rd": ("l", 8, 0, 2),
    "Henderson": ("l", 8, 0, 0), "Sunnyvale": ("l", 8, -3, 2), "Glen Eden": ("t", 0, 8, 2),
    "Fruitvale": ("t", 0, 8, 2), "New Lynn": ("t", 0, 8, 0), "Avondale": ("t", 0, 8, 2),
    "Mt Albert": ("t", 0, 8, 1), "Baldwin Ave": ("r", -8, -3, 2), "Morningside": ("r", -8, -3, 2),
    "Kingsland": ("r", -8, -3, 1), "Maungawhau": ("r", -9, -3, 0),
    "Karanga-a-Hape": ("r", -9, 0, 0), "Te Waihorotiu": ("r", -9, 0, 0),
    "Waitemata": ("b", 0, -9, 0), "Parnell": ("r", -8, 0, 1), "Grafton": ("t", 0, 9, 0),
    "Newmarket": ("l", 9, -3, 0), "Orakei": ("b", 0, -8, 1), "Meadowbank": ("t", 0, 8, 2),
    "Glen Innes": ("r", -8, 0, 1), "Panmure": ("r", -8, 0, 1), "Sylvia Park": ("r", -8, -3, 1),
    "Remuera": ("l", 8, -2, 2), "Greenlane": ("l", 8, -2, 2), "Ellerslie": ("r", -8, 0, 1),
    "Penrose": ("r", -8, 0, 0), "Te Papapa": ("r", -8, 0, 2), "Onehunga": ("r", -8, 0, 0),
    "Otahuhu": ("l", 9, 0, 0), "Middlemore": ("r", -9, 0, 1), "Papatoetoe": ("r", -9, 0, 1),
    "Puhinui": ("r", -9, 0, 0), "Homai": ("r", -9, 0, 2), "Manurewa": ("r", -9, 0, 2),
    "Te Mahia": ("r", -9, 0, 2), "Takaanini": ("r", -9, 0, 2), "Papakura": ("r", -9, 0, 0),
    "Drury": ("r", -9, 0, 2), "Paerata": ("r", -9, 0, 2), "Pukekohe": ("r", -9, 0, 0),
    "Manukau": ("t", 0, 9, 0),
}

# the soft land/water shapes and volcanic cones behind the map (railview's)
LAND = [[(0, 46), (110, 46), (140, 28), (330, 28), (330, 250), (206, 250), (190, 200),
         (150, 178), (96, 170), (40, 186), (0, 176)]]
LAND_ROUND = (-10, 48, 60, 152, 18)                       # a rounded rectangle
WATER = [[(300, 60), (330, 50), (330, 150), (310, 124), (304, 90)],
         [(170, 250), (180, 186), (214, 170), (232, 182), (236, 250)]]
CONES = [(150, 104, 9), (218, 138, 10), (110, 104, 6), (246, 72, 7), (190, 116, 6),
         (286, 162, 8), (56, 150, 7), (232, 58, 5)]
CRL_LOOP = [(158, 70), (158, 38), (216, 38), (216, 88), (158, 88), (158, 70)]


def api(path):
    req = urllib.request.Request("https://api.at.govt.nz" + path,
                                 headers={"Ocp-Apim-Subscription-Key": KEY,
                                          "Accept": "application/json"})
    return json.load(urllib.request.urlopen(req, timeout=60))


def floats(seq, nd=2):
    return ",".join(("%." + str(nd) + "f") % v for v in seq)


def kstr(s):
    return '"' + (s.replace("\\", "\\\\").replace('"', '\\"').replace("$", "\\$")
                  .replace("\n", "\\n")) + '"'


def stops_table():
    path = os.path.join(HERE, "stops.json")
    if not os.path.exists(path):
        json.dump(api("/gtfs/v3/stops"), open(path, "w"))
    return [s["attributes"] for s in json.load(open(path))["data"]]


def gen_map(stops):
    names = list(R.STATIONS.keys())
    idx = {n: i for i, n in enumerate(names)}
    parents = {s["stop_id"]: s for s in stops
               if s.get("location_type") == 1 and "Train Station" in s["stop_name"]}
    by_base = {p["stop_name"].replace(" Train Station", "").strip(): pid for pid, p in parents.items()}
    plat = {}
    for s in stops:
        if s.get("parent_station") in parents:
            plat.setdefault(s["parent_station"], []).append((s["stop_id"], s.get("platform_code") or ""))
    lines_of = {n: 0 for n in names}
    for li, (_, _, _, seq) in enumerate(R.LINES):
        for n in seq:
            lines_of[n] |= 1 << li
    real = json.load(open(os.path.join(HERE, "tools", "stations.json")))

    out = ["// Generated by tools/gen_data.py -- the post-CRL network schematic.",
           "package nz.aryan.akllive.data", "",
           "object MapData {",
           "    const val W = 320f",
           "    const val H = 240f",
           "    val LINE_IDS = arrayOf(%s)" % ", ".join(kstr(l[0]) for l in R.LINES),
           "    val LINE_NAMES = arrayOf(%s)" % ", ".join(kstr(l[1]) for l in R.LINES),
           "    val LINE_COLORS = longArrayOf(%s)" % ", ".join(
               "0xFF%02X%02X%02X" % l[2] for l in R.LINES),
           "    // drawing paths (corners already rounded), x,y pairs in map units",
           "    val LINE_DRAW: List<FloatArray> = listOf("]
    for li in range(len(R.LINES)):
        pts = [(x, y) for _, x, y in R.LINE_PATHS[li]]
        f = R._fillet(pts, 6)
        out.append("        f(%s)," % kstr(floats([c for p in f for c in p])))
    out.append("    )")
    out.append("    val CRL_LOOP = f(%s)" % kstr(floats([c for p in R._fillet(CRL_LOOP, 7) for c in p])))
    out.append("    val LAND: List<FloatArray> = listOf(%s)" % ", ".join(
        "f(%s)" % kstr(floats([c for p in poly for c in p], 0)) for poly in LAND))
    out.append("    val LAND_ROUND = floatArrayOf(%s)" % ", ".join("%sf" % v for v in LAND_ROUND))
    out.append("    val WATER: List<FloatArray> = listOf(%s)" % ", ".join(
        "f(%s)" % kstr(floats([c for p in poly for c in p], 0)) for poly in WATER))
    out.append("    val CONES = f(%s)" % kstr(floats([c for t in CONES for c in t], 0)))
    out.append("")
    out.append("    // key, name, per-line points (x,y pairs), lat, lon, lines bitmask,")
    out.append("    // label anchor/dx/dy/priority, crl, platforms (stop id=platform;...)")
    out.append("    val STATIONS: List<Station> = listOf(")
    for n in names:
        pts = R.STATIONS[n]
        a, dx, dy, pr = LABEL[n]
        pid = by_base[GTFS_NAME.get(n, n)]
        ps = ";".join("%s=%s" % (sid, code) for sid, code in sorted(plat.get(pid, []), key=lambda p: p[1]))
        la, lo = real[n]
        out.append("        Station(%s, %s, f(%s), %.5f, %.5f, %d, '%s', %df, %df, %d, %s, %s)," % (
            kstr(n), kstr(DISPLAY.get(n, n)), kstr(floats([c for p in pts for c in p])),
            la, lo, lines_of[n], a, dx, dy, pr, "true" if n in R.CRL else "false", kstr(ps)))
    out.append("    )")
    out.append("")
    out.append("    // GPS snapping: line, from/to station index, path between them, real ends")
    out.append("    val SEGS: List<Seg> = listOf(")
    for li, a, b, poly, (la0, lo0), (la1, lo1) in R.SEGS:
        out.append("        Seg(%d, %d, %d, f(%s), %.5f, %.5f, %.5f, %.5f)," % (
            li, idx[a], idx[b], kstr(floats([c for p in poly for c in p])), la0, lo0, la1, lo1))
    out.append("    )")
    out.append("}")
    out.append("")
    out.append("class Station(")
    out.append("    val key: String, val name: String, val pts: FloatArray, val lat: Double,")
    out.append("    val lon: Double, val lines: Int, val anchor: Char, val dx: Float, val dy: Float,")
    out.append("    val priority: Int, val crl: Boolean, platformSpec: String,")
    out.append(") {")
    out.append("    val x = (0 until pts.size / 2).map { pts[it * 2] }.average().toFloat()")
    out.append("    val y = (0 until pts.size / 2).map { pts[it * 2 + 1] }.average().toFloat()")
    out.append("    /** platform stop id -> platform number */")
    out.append("    val platforms: Map<String, String> = platformSpec.split(';').filter { it.isNotEmpty() }")
    out.append("        .associate { it.substringBefore('=') to it.substringAfter('=') }")
    out.append("    val interchange get() = pts.size > 2 || crl")
    out.append("}")
    out.append("")
    out.append("class Seg(val line: Int, val from: Int, val to: Int, val poly: FloatArray,")
    out.append("          val lat0: Double, val lon0: Double, val lat1: Double, val lon1: Double)")
    out.append("")
    out.append("internal fun f(s: String): FloatArray = s.split(',').map { it.toFloat() }.toFloatArray()")
    open(os.path.join(OUT, "MapData.kt"), "w", encoding="utf-8").write("\n".join(out) + "\n")
    print("MapData.kt: %d stations, %d segments" % (len(names), len(R.SEGS)))


def gen_routes(stops):
    by_id = {s["stop_id"]: s for s in stops}
    now = datetime.datetime.now(datetime.timezone(datetime.timedelta(hours=12)))
    routes = []
    for code, label in (("8669", "to Britomart"), ("8664", "to Waikowhai")):
        sid = api("/gtfs/v3/stops?filter%5Bstop_code%5D=" + code)["data"][0]["id"]
        trip = None
        for h in range(6, 20):
            j = api("/gtfs/v3/stops/%s/stoptrips?filter%%5Bdate%%5D=%s&filter%%5Bstart_hour%%5D=%d"
                    "&hour_range=2" % (sid, now.strftime("%Y-%m-%d"), h))
            for e in j.get("data", []):
                if e["attributes"]["route_id"].startswith("27H"):
                    trip = e["attributes"]["trip_id"]
                    break
            if trip:
                break
        st = api("/gtfs/v3/trips/%s/stoptimes" % trip)["data"]
        seq = sorted(st, key=lambda x: x["attributes"]["stop_sequence"])
        rows = []
        for x in seq:
            s = by_id[x["attributes"]["stop_id"]]
            rows.append("%s|%s|%.5f|%.5f" % (s["stop_code"], s["stop_name"], s["stop_lat"], s["stop_lon"]))
        routes.append((code, label, rows))
        print("27H %s: %d stops (%s -> %s)" % (label, len(rows), rows[0].split("|")[1], rows[-1].split("|")[1]))
    out = ["// Generated by tools/gen_data.py -- the 27H's stops, in order, both ways.",
           "package nz.aryan.akllive.data", "",
           "object RouteData {",
           "    /** our stop code -> (direction label, stops as code|name|lat|lon) */",
           "    val ROUTES: Map<String, Pair<String, List<RouteStop>>> = mapOf("]
    for code, label, rows in routes:
        out.append("        %s to (%s to parse(%s))," % (kstr(code), kstr(label), kstr("\n".join(rows))))
    out += ["    )", "",
            "    private fun parse(s: String) = s.split('\\n').map {",
            "        val p = it.split('|')",
            "        RouteStop(p[0], p[1], p[2].toDouble(), p[3].toDouble())",
            "    }", "}", "",
            "class RouteStop(val code: String, val name: String, val lat: Double, val lon: Double)"]
    open(os.path.join(OUT, "RouteData.kt"), "w", encoding="utf-8").write("\n".join(out) + "\n")


if __name__ == "__main__":
    os.makedirs(OUT, exist_ok=True)
    stops = stops_table()
    gen_map(stops)
    gen_routes(stops)
